#! /usr/bin/perl -w

# Need some thought on when the templates should be expanded and when the action should be called.

use esmith::Build::CreateLinks qw(:all);
my $event = "printpdf-update";

foreach (qw(
       /etc/crontab
    ))
{
    templates2events("$_", qw(
    post-upgrade
    console-save
    bootstrap-console-save
    ));
}

#--------------------------------------------------
# actions for ipsec-update event
#--------------------------------------------------

event_link("printpdf-update", $event, "10");

